version: '3.4'

services:
    ollamadeepseek: 
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
           - '11434:11434'
        environment:
            OLLAMA_HOST: 0.0.0.0
            OLLAMA_PORT: 11434
