name: Cron Run News Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
    - cron: "0 17 * * *"

jobs:
  run-news-fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker Images
      run: |
        docker pull rwencik/summarize-pt
        docker pull rwencik/news

    - name: Create a Custom Docker Network
      run: docker network create network

    - name: Start Summarization Service
      run: |
        docker run -d --name summarize_service \
                   --network network \
                   -p 8000:8000 \
                   rwencik/summarize-pt

    - name: Wait for Summarization Service to Be Ready
      run: |
        echo "Waiting for summarize-pt service to start..."
        for i in {1..30}; do
          if curl -s http://localhost:8000/docs > /dev/null; then
            echo "Summarization service is up!"
            exit 0
          fi
          echo "Waiting..."
          sleep 3
        done
        echo "Summarization service failed to start"
        exit 1

    - name: Run News Fetcher
      env:
        RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      run: |
        docker run --network network \
                   -e RSS_FEED_URL="${RSS_FEED_URL}" \
                   -e EMAIL_SENDER="${EMAIL_SENDER}" \
                   -e EMAIL_PASSWORD="${EMAIL_PASSWORD}" \
                   -e EMAIL_RECIPIENTS="${EMAIL_RECIPIENTS}" \
                   rwencik/news
