name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub using credentials stored as GitHub Secrets
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t rwencik/news:latest pegar-noticias/

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t rwencik/summarize-pt:latest ai/

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push rwencik/news:latest

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push rwencik/summarize-pt:latest
