name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Extract branch name and sanitize it for Docker tag
    - name: Set branch name as Docker tag
      run: echo "BRANCH_TAG=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_ENV

    # Log in to Docker Hub using credentials stored as GitHub Secrets
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build and tag Docker images with both branch name and 'latest' if it's main
    - name: Build and Push News Docker image
      run: |
        docker build -t rwencik/news:${{ env.BRANCH_TAG }} pegar-noticias/
        [ "${{ env.BRANCH_TAG }}" == "main" ] && docker tag rwencik/news:${{ env.BRANCH_TAG }} rwencik/news:latest
        docker push rwencik/news:${{ env.BRANCH_TAG }}
        [ "${{ env.BRANCH_TAG }}" == "main" ] && docker push rwencik/news:latest

    - name: Build and Push DeepSeek Docker image
      run: |
        docker build -t rwencik/deepseek:${{ env.BRANCH_TAG }} ai/
        [ "${{ env.BRANCH_TAG }}" == "main" ] && docker tag rwencik/deepseek:${{ env.BRANCH_TAG }} rwencik/deepseek:latest
        docker push rwencik/deepseek:${{ env.BRANCH_TAG }}
        [ "${{ env.BRANCH_TAG }}" == "main" ] && docker push rwencik/deepseek:latest