name: Run News Fetch

on:
  workflow_dispatch:

jobs:
  run-news-fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker Images
      run: |
        docker pull rwencik/summarize-pt
        docker pull rwencik/news

    - name: Create a Custom Docker Network
      run: docker network create network

    - name: Start Summarization Service
      run: |
        docker run -d --name summarize_service \
                   --network network \
                   -p 8000:8000 \
                   rwencik/summarize-pt

    - name: Run News Fetcher
      env:
        RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      run: |
        docker run --network network \
                   -e RSS_FEED_URL="${RSS_FEED_URL}" \
                   -e EMAIL_SENDER="${EMAIL_SENDER}" \
                   -e EMAIL_PASSWORD="${EMAIL_PASSWORD}" \
                   -e EMAIL_RECIPIENTS="${EMAIL_RECIPIENTS}" \
                   rwencik/news
